[project]
name = "aljabr"
version = "0.5.0"
description = "Linear operators interfaces"
authors = [
    { name = "François Orieux", email = "francois.orieux@universite-paris-saclay.fr" }
]
maintainers = [
    { name = "François Orieux", email = "francois.orieux@universite-paris-saclay.fr" }
]
readme = "README.md"
license = "MIT"
keywords = ["linear algebra", "implicit operator"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: Implementation :: CPython",
    "Typing :: Typed",]
requires-python = ">=3.12"
dependencies = [
    "array-api-compat>=1.13.0",
    "numpy>=2.4.1",
    "udft>=4.0.2",
]

[project.urls]
homepage = "https://aljabr.readthedocs.io/"
documentation = "https://udft.readthedocs.io/"
repository = "https://github.com/forieux/aljabr/"
changelog = "https://github.com/forieux/aljabr/blob/main/CHANGELOG.md"
"Bug Tracker" = "https://github.com/forieux/aljabr/issues"
"Author webpage" = "https://pro.orieux.fr/"

[project.optional-dependencies]
wavelet = [
    "pywavelets>=1.9.0",
]
scipy = [
    "scipy>=1.17.1",
]
docs = [
    "sphinx>=7",
    "furo",
    "myst-parser",
]

[dependency-groups]
dev = [
    "ipython>=9.9.0",
    "pytest>=8",
]

[build-system]
requires = ["uv_build>=0.11.15,<0.12"]
build-backend = "uv_build"

[tool.hatch.build.targets.wheel]
packages = ["src/aljabr"]

[tool.pytest.ini_options]
testpaths = ["tests"]
