[project]
name = "aljabr"
version = "0.4.0"
description = "Linear operators interfaces"
authors = [
    { name = "François Orieux", email = "francois.orieux@universite-paris-saclay.fr" }
]
maintainers = [
    { name = "François Orieux", email = "francois.orieux@universite-paris-saclay.fr" }
]
readme = "README.md"
license = "Public Domain"
keywords = ["linear algebra", "implicit operator"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: Implementation :: CPython",
    "Typing :: Typed",]
include = ["py.typed", "LICENSE"]
packages = [{include = "aljabr", from = "src"}]
requires-python = ">=3.12"
dependencies = [
    "array-api-compat>=1.13.0",
    "numpy>=2.4.1",
    "udft>=4.0.2",
]

[project.urls]
repository = "https://github.com/forieux/aljabr/"
changelog = "https://github.com/forieux/aljabr/blob/main/CHANGELOG.md"
"Bug Tracker" = "https://github.com/forieux/aljabr/issues"
"Author webpage" = "https://pro.orieux.fr/"

[project.optional-dependencies]
wavelet = [
    "pywavelets>=1.9.0",
]
scipy = [
    "scipy>=1.17.1",
]
docs = [
    "sphinx>=7",
    "furo",
    "myst-parser",
]

[dependency-groups]
dev = [
    "ipython>=9.9.0",
]
